apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: date-time-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: date-time-app  # Target Deployment name
  minReplicas: 2  # Minimum pods
  maxReplicas: 5  # Maximum pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Scale when CPU usage >50%
