apiVersion: v1
kind: Service
metadata:
  name: date-time-service
spec:
  type: NodePort
  selector:
    app: date-time-app  # Match the label in deployment
  ports:
    - protocol: TCP
      port: 5000         # Exposed service port
      targetPort: 5000   # Container's port
